name: Build static site using coltrane
on:
  schedule: # Run workflow automatically
    - cron: '30 8 */2 * *'
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
  push:
    branches:
      - main

jobs:
  update-dates-and--build-static-site:
    name: Update dates and build static site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Pull and rebase before any work
        run: |-
          git config --global user.email "tobidegnon@proton.me"
          git config --global user.name "Tobi DEGNON"
          git pull --rebase

      - name: Update projects date
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: just pw projects update-dates

      - name: Build static site
        run: just build

      - name: Commit and push if docs folder content changed
        run: |-
          git diff --quiet || (git commit -am "build static site")
          git push

     
