name: Build static site using coltrane
on:
  schedule: # Run workflow automatically
    - cron: '30 8 */2 * *'
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  update-projects-with-latest-dates:
    name: Update this repo's data/projects.json file with each project latest commit date
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - shell: bash
        env:
          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
        run: |
          python projects.py update-dates

      - name: Commit and push if projects.json changed
        run: |-
          git config --global user.email "tobidegnon@proton.me"
          git config --global user.name "Tobi DEGNON"
          git diff --quiet || (git add data/projects.json && git commit -m "Updated projects.json with latest commit dates")
          git push

  build-with-coltrane:
    name: Build static site with coltrane
    needs: [update-projects-with-latest-dates]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up poetry
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - uses: actions/cache@v2
        name: Configure pip caching
        with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            restore-keys: |
              ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Run Coltrane record
        run: |-
          coltrane record --output docs --force

      - name: Commit and push if docs folder content changed
        run: |-
          git pull --rebase
          git config --global user.email "tobidegnon@proton.me"
          git config --global user.name "Tobi DEGNON"
          git diff --quiet || (git add docs/* && git commit -m "build static site")
          git push
